import { readdirSync, statSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, relative, posix, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { RouteMeta, RequestExample } from '../src/types.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

const DATA_DIR = join(__dirname, '..', 'src', 'data');
const OUT_FILE = join(__dirname, '..', 'src', 'generated', 'routes.ts');
const OPENAPI_TS_FILE = join(__dirname, '..', 'src', 'generated', 'openapi.ts');
const OPENAPI_JSON_FILE = join(__dirname, '..', 'src', 'generated', 'openapi.json');

const { mockConfig } = await import('../mock.config.js');

interface RouteEntry {
  importName: string;
  importPath: string;
  routePath: string;
  method: string;
}

function scan(dir: string, entries: RouteEntry[] = []): RouteEntry[] {
  for (const name of readdirSync(dir)) {
    const fullPath = join(dir, name);
    const st = statSync(fullPath);
    if (st.isDirectory()) {
      scan(fullPath, entries);
    } else if (st.isFile() && name.endsWith('.ts')) {
      const method = name.replace(/\.ts$/, '');
      if (!['GET', 'POST', 'PUT', 'PATCH', 'DELETE'].includes(method)) continue;

      const relDir = relative(DATA_DIR, dir);
      const routePath = relDir.split(sep).join(posix.sep);
      const importPath = '../data/' + (routePath ? routePath + '/' : '') + method + '.js';
      const importName = 'route_' + routePath.replace(/[^a-zA-Z0-9]/g, '_') + '_' + method;

      entries.push({ importName, importPath, routePath, method });
    }
  }
  return entries;
}

function matchGroup(routePath: string): string | undefined {
  for (const [groupName, patterns] of Object.entries(mockConfig.groups)) {
    for (const pattern of patterns) {
      if (pattern.endsWith('/*')) {
        const prefix = pattern.slice(0, -2);
        if (routePath === prefix || routePath.startsWith(prefix + '/')) {
          return groupName;
        }
      } else if (routePath === pattern) {
        return groupName;
      }
    }
  }
  return undefined;
}

function buildRoutes(entries: RouteEntry[]) {
  const imports = entries
    .map((e) => `import * as ${e.importName} from '${e.importPath}';`)
    .join('\n');

  const routeMap: Record<string, Record<string, string>> = {};
  for (const e of entries) {
    routeMap[e.routePath] ||= {};
    routeMap[e.routePath][e.method] = e.importName;
  }

  const manifest = Object.entries(routeMap)
    .map(([path, methods]) => {
      const ms = Object.entries(methods)
        .map(([method, importName]) => {
          return `    ${method}: {\n      data: ${importName}.data,\n      scenarios: (${importName} as any).scenarios,\n      meta: (${importName} as any).meta,\n    },`;
        })
        .join('\n');
      return `  '${path}': {\n${ms}\n  },`;
    })
    .join('\n');

  const registry = Object.entries(routeMap)
    .map(([path, methods]) => {
      const ms = Object.entries(methods)
        .map(([method, importName]) => `    ${method}: Object.keys((${importName} as any).scenarios || {}),`)
        .join('\n');
      return `  '${path}': {\n${ms}\n  },`;
    })
    .join('\n');

  const content = `// Auto-generated by scripts/build-routes.ts\n// Do not edit manually\n\nimport type { RouteManifest, ScenarioRegistry } from '../types.js';\n${imports}\n\nexport const manifest: RouteManifest = {\n${manifest}\n};\n\nexport const registry: ScenarioRegistry = {\n${registry}\n};\n`;

  writeFileSync(OUT_FILE, content, 'utf-8');
  console.log(`Generated ${entries.length} routes → src/generated/routes.ts`);
}

function inferSchema(value: unknown, isMultipart = false): Record<string, unknown> {
  if (value === null) return { type: 'null' };
  if (Array.isArray(value)) {
    return {
      type: 'array',
      items: value.length > 0 ? inferSchema(value[0], isMultipart) : { type: 'object' },
    };
  }
  if (typeof value === 'object') {
    return {
      type: 'object',
      properties: Object.fromEntries(
        Object.entries(value as Record<string, unknown>).map(([k, v]) => [k, inferSchema(v, isMultipart)])
      ),
    };
  }
  if (typeof value === 'string') {
    // For multipart/form-data, treat as file upload if looks like file placeholder
    if (isMultipart && (value === 'binary' || value.startsWith('file_'))) {
      return { type: 'string', format: 'binary', description: 'File upload' };
    }
    return { type: 'string', example: value };
  }
  if (typeof value === 'number') return { type: 'number', example: value };
  if (typeof value === 'boolean') return { type: 'boolean', example: value };
  return { type: 'string' };
}

async function buildOpenApi(entries: RouteEntry[]) {
  const paths: Record<string, Record<string, unknown>> = {};

  for (const e of entries) {
    const openApiPath = (mockConfig.basePath === '' ? '' : mockConfig.basePath) + '/' + e.routePath.replace(/{(\w+)}/g, '{$1}');
    if (!paths[openApiPath]) {
      paths[openApiPath] = {};
    }

    const modulePath = join(DATA_DIR, e.routePath, `${e.method}.ts`);
    let meta: RouteMeta | undefined;
    let requests: Record<string, RequestExample> | undefined;
    try {
      const mod = await import(modulePath);
      meta = mod.meta;
      requests = mod.requests;
    } catch {
      // ignore
    }

    const group = matchGroup(e.routePath);
    const tags = group ? [group] : ['other'];

    const operation: Record<string, unknown> = {
      summary: meta?.description || `${e.method} ${openApiPath}`,
      tags,
      responses: {
        '200': {
          description: 'Successful response',
          content: {
            'application/json': {
              schema: { type: 'object' },
            },
          },
        },
      },
    };

    // Security
    if (mockConfig.securitySchemes && Object.keys(mockConfig.securitySchemes).length > 0) {
      if (meta?.security !== false) {
        // route-level override or global default
        const routeSecurity = meta?.security || mockConfig.security;
        if (routeSecurity && routeSecurity.length > 0) {
          operation.security = routeSecurity.map((scheme) => ({ [scheme]: [] }));
        }
      }
    }

    // Headers parameters (global + route-level)
    const headers: Array<Record<string, unknown>> = [];
    for (const h of mockConfig.globalHeaders || []) {
      headers.push({
        name: h.name,
        in: 'header',
        description: h.description,
        required: h.required ?? false,
      });
    }
    for (const h of meta?.headers || []) {
      // avoid duplicate global
      if (!headers.some((hh) => hh.name === h.name)) {
        headers.push({
          name: h.name,
          in: 'header',
          description: h.description,
          required: h.required ?? false,
        });
      }
    }
    if (headers.length > 0) {
      operation.parameters = headers;
    }

    // Add requestBody for methods that accept body
    if (['POST', 'PUT', 'PATCH'].includes(e.method) && (meta?.request || requests)) {
      const content: Record<string, unknown> = {};
      
      // Group requests by contentType
      const byContentType: Record<string, Record<string, RequestExample>> = {};
      
      if (requests) {
        for (const [name, req] of Object.entries(requests)) {
          const ct = req.contentType || 'application/json';
          byContentType[ct] ||= {};
          byContentType[ct][name] = req;
        }
      }
      
      // Add meta.request as default example for application/json if no requests
      if (meta?.request && !byContentType['application/json']) {
        byContentType['application/json'] = {
          default: {
            summary: 'Default',
            value: meta.request,
          },
        };
      }

      // Generate content for each contentType
      for (const [ct, examples] of Object.entries(byContentType)) {
        const firstReq = Object.values(examples)[0];
        
        content[ct] = {
          schema: inferSchema(firstReq.value, ct === 'multipart/form-data'),
          examples: Object.fromEntries(
            Object.entries(examples).map(([name, req]) => [
              name,
              {
                summary: req.summary || name,
                description: req.description,
                value: req.value,
              },
            ])
          ),
        };
      }

      operation.requestBody = {
        description: 'Request body',
        required: true,
        content,
      };
    }

    paths[openApiPath][e.method.toLowerCase()] = operation;
  }

  const openApiSpec: Record<string, unknown> = {
    openapi: '3.0.3',
    info: mockConfig.info,
    servers: mockConfig.servers,
    paths,
    tags: Object.entries(mockConfig.groups).map(([name]) => ({ name })).concat([{ name: 'other' }]),
  };

  // Security schemes
  if (mockConfig.securitySchemes && Object.keys(mockConfig.securitySchemes).length > 0) {
    openApiSpec.components = {
      securitySchemes: mockConfig.securitySchemes,
    };
  }

  if (mockConfig.externalDocs) {
    openApiSpec.externalDocs = mockConfig.externalDocs;
  }

  // Generate TS module
  const tsContent = `// Auto-generated by scripts/build-routes.ts\n// Do not edit manually\n\nexport default ${JSON.stringify(openApiSpec, null, 2)};\n`;
  writeFileSync(OPENAPI_TS_FILE, tsContent, 'utf-8');
  console.log(`Generated OpenAPI spec → src/generated/openapi.ts`);

  // Generate JSON file for hot reload
  const jsonContent = JSON.stringify(openApiSpec, null, 2);
  writeFileSync(OPENAPI_JSON_FILE, jsonContent, 'utf-8');
  console.log(`Generated OpenAPI JSON → src/generated/openapi.json`);
}

function detectCollision(entries: RouteEntry[], configPath: string, type: string) {
  const normalizedPath = configPath.replace(/^\//, '');
  for (const e of entries) {
    if (e.routePath === normalizedPath || e.routePath.startsWith(normalizedPath + '/')) {
      throw new Error(
        `COLLISION: ${type} path "${configPath}" conflicts with API route "${e.routePath}". ` +
        `Please change ${type}Path in mock.config.ts to avoid conflict.`
      );
    }
  }
}

async function build() {
  const entries = scan(DATA_DIR);
  detectCollision(entries, mockConfig.openApiPath, 'openApi');
  detectCollision(entries, mockConfig.docsPath, 'docs');

  mkdirSync(join(__dirname, '..', 'src', 'generated'), { recursive: true });

  buildRoutes(entries);
  await buildOpenApi(entries);
}

build().catch((err) => {
  console.error('Build failed:', err);
  process.exit(1);
});
